### ISSUE TITLE
Why is the `requestClient` separated & not instantiated everytime?

### ISSUE THREAD

**Issue by deadcoder0904** [alkihis/twitter-api-v2-user-oauth-flow-example#1]
https://github.com/alkihis/twitter-api-v2-user-oauth-flow-example/blob/d878b036c86c21c97181fbf613aca7d2f5d591b7/src/config.ts#L13

I don't understand why this is instantiated only once & exported while the `tempClient` isn't?

https://github.com/alkihis/twitter-api-v2-user-oauth-flow-example/blob/d878b036c86c21c97181fbf613aca7d2f5d591b7/src/routes/callback.ts#L40

So when I use my app for calling APIs like fetch tweets, do I use `requestClient` afterwards?

Another question: If I use `authenticate` during login, it'll automatically authorize for the first time, right? And then automatically `authenticate` next time onwards so I don't have to put any option like `linkMode` right? I feel like the option `{ linkMode: 'authorize' }` or even `{ linkMode: 'authenticate' }` seem useless then.

**Comment by alkihis** [comment]
For the first question, the answer is as simple as question: `requestClient` can only make requests to **obtain request tokens**.
**tempClient** cannot be global because it is instanciated with **tokens obtained in session**.

You cannot make requests with **neither of those clients**, you need to create a new client with definitive tokens (as noted in comments in `/callback` route).
This kind of stuff is highly documented in [Twitter documentation](https://developer.twitter.com/en/docs/authentication/oauth-1-0a/obtaining-user-access-tokens), please relate to it.

---

Link mode is `authenticate` by default, means that user has to accept permissions only for the first time of using your app.
If you choose to use `authorize`, user must re-validate permissions when he clicks on the link.
This parameter is only **applicable for current link**, and will not affect future connections of users.

**Comment by deadcoder0904** [comment]
@alkihis Regarding `authenticate` & `authorize`, on my web app, if I put nothing, it'll default to `authenticate` & it makes the flow perfect like on a real-world app. Is that correct? Just confirming.

**Comment by alkihis** [comment]
Yep, auth mode is authenticate by default, as we can except in a real-world app.
